/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.saipsc.Visao.MenuPrincipalP;

import com.mycompany.saipsc.Visao.Aluno.CadAluno;
import com.mycompany.saipsc.Visao.Aluno.ListAluno;
import com.mycompany.saipsc.Visao.Campeonato.CadCampeonato;
import com.mycompany.saipsc.Visao.Campeonato.ListCampeonato;
import com.mycompany.saipsc.ferramentas.BancoDeDadosMySql;
import com.mycompany.saipsc.ferramentas.Constantes;
import com.mycompany.saipsc.ferramentas.DadosTemporarios;
import com.mycompany.saipsc.ferramentas.Formularios;
import com.mycompany.saipsc.visao.Acesso.CadAcesso;
import com.mycompany.saipsc.visao.Acesso.ListAcesso;
import com.mycompany.saipsc.visao.Cargo.CadCargo;
import com.mycompany.saipsc.visao.Cargo.ListCargo;
import com.mycompany.saipsc.Visao.CategoriaU.CadCategoriaU;
import com.mycompany.saipsc.Visao.CategoriaU.ListCategoriaU;
import com.mycompany.saipsc.visao.Condicao.CadCondicao;
import com.mycompany.saipsc.visao.Condicao.ListCondicao;
import com.mycompany.saipsc.visao.Cor.CadCor;
import com.mycompany.saipsc.visao.Cor.ListCor;
import com.mycompany.saipsc.visao.Equipe.CadEquipe;
import com.mycompany.saipsc.visao.Equipe.ListEquipe;
import com.mycompany.saipsc.visao.Investidores.CadInvestidores;
import com.mycompany.saipsc.visao.Investidores.ListInvestidores;
import com.mycompany.saipsc.Visao.Uniforme.CadUniforme;
import com.mycompany.saipsc.Visao.Uniforme.ListUnifome;
import com.mycompany.saipsc.visao.Marca.CadMarca;
import com.mycompany.saipsc.visao.Marca.ListMarca;
import com.mycompany.saipsc.visao.Participacao.CadParticipacao;
import com.mycompany.saipsc.visao.Participacao.ListParticipacao;
import com.mycompany.saipsc.visao.Patrimonio.CadPatrimonio;
import com.mycompany.saipsc.visao.Patrimonio.ListPatrimonio;
import com.mycompany.saipsc.visao.Pessoa.CadPessoa;
import com.mycompany.saipsc.visao.Pessoa.ListPessoa;
import com.mycompany.saipsc.visao.Polos.CadPolos;
import com.mycompany.saipsc.visao.Polos.ListPolos;
import com.mycompany.saipsc.visao.Tamanho.CadTamanho;
import com.mycompany.saipsc.visao.Tamanho.ListTamanho;
import static java.awt.Frame.MAXIMIZED_BOTH;
import javax.swing.JOptionPane;

/**
 *
 * @author Batista
 */
public class MenuProfessores extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuProfessores() {
        initComponents();
    
        setLocationRelativeTo(null);
        
        setExtendedState(MAXIMIZED_BOTH);
        
        if (!BancoDeDadosMySql.conectar()){
            JOptionPane.showMessageDialog(null, "Não foi possível conectar ao banco de dados. O sistema será finalizado.");
            System.exit(0);
        }

    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmcParticipacao = new javax.swing.JMenu();
        jMCAcesso = new javax.swing.JMenuItem();
        jMCAluno = new javax.swing.JMenuItem();
        jmcCampeonato = new javax.swing.JMenuItem();
        jmcCargo = new javax.swing.JMenuItem();
        jmcCategoriaKF = new javax.swing.JMenuItem();
        jmcCondicao = new javax.swing.JMenuItem();
        jmcCor = new javax.swing.JMenuItem();
        jmcEquipe = new javax.swing.JMenuItem();
        jmcInvestidores = new javax.swing.JMenuItem();
        jmcKimonoF = new javax.swing.JMenuItem();
        jmcMarca = new javax.swing.JMenuItem();
        jmCParticipacao = new javax.swing.JMenuItem();
        jmcPatrimonio = new javax.swing.JMenuItem();
        jmcPessoa = new javax.swing.JMenuItem();
        jmcPolos = new javax.swing.JMenuItem();
        jmcTamanho = new javax.swing.JMenuItem();
        jMenuListar = new javax.swing.JMenu();
        jMLAcesso = new javax.swing.JMenuItem();
        jMLAluno = new javax.swing.JMenuItem();
        jmlCampeonato = new javax.swing.JMenuItem();
        jmlCargo = new javax.swing.JMenuItem();
        jmlCategoriaKF = new javax.swing.JMenuItem();
        jmlCondicao = new javax.swing.JMenuItem();
        jmlCor = new javax.swing.JMenuItem();
        jmlEquipe = new javax.swing.JMenuItem();
        jmlInvestidores = new javax.swing.JMenuItem();
        jmlKimonoF = new javax.swing.JMenuItem();
        jmlMarca = new javax.swing.JMenuItem();
        jmlParticipacao = new javax.swing.JMenuItem();
        jmlPatrimonio = new javax.swing.JMenuItem();
        jmlPessoa = new javax.swing.JMenuItem();
        jMenuItem27 = new javax.swing.JMenuItem();
        jmlTamano = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setText("SAI");

        jLabel2.setText("Professores");

        jmcParticipacao.setText("Cadastrar");

        jMCAcesso.setText("Acesso");
        jMCAcesso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMCAcessoActionPerformed(evt);
            }
        });
        jmcParticipacao.add(jMCAcesso);

        jMCAluno.setText("Aluno");
        jMCAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMCAlunoActionPerformed(evt);
            }
        });
        jmcParticipacao.add(jMCAluno);

        jmcCampeonato.setText("Competições");
        jmcCampeonato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmcCampeonatoActionPerformed(evt);
            }
        });
        jmcParticipacao.add(jmcCampeonato);

        jmcCargo.setText("Cargo");
        jmcCargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmcCargoActionPerformed(evt);
            }
        });
        jmcParticipacao.add(jmcCargo);

        jmcCategoriaKF.setText("Categoria uniforme");
        jmcCategoriaKF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmcCategoriaKFActionPerformed(evt);
            }
        });
        jmcParticipacao.add(jmcCategoriaKF);

        jmcCondicao.setText("Condicao");
        jmcCondicao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmcCondicaoActionPerformed(evt);
            }
        });
        jmcParticipacao.add(jmcCondicao);

        jmcCor.setText("Cor");
        jmcCor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmcCorActionPerformed(evt);
            }
        });
        jmcParticipacao.add(jmcCor);

        jmcEquipe.setText("Equipe");
        jmcEquipe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmcEquipeActionPerformed(evt);
            }
        });
        jmcParticipacao.add(jmcEquipe);

        jmcInvestidores.setText("Investidores");
        jmcInvestidores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmcInvestidoresActionPerformed(evt);
            }
        });
        jmcParticipacao.add(jmcInvestidores);

        jmcKimonoF.setText("Uniforme");
        jmcKimonoF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmcKimonoFActionPerformed(evt);
            }
        });
        jmcParticipacao.add(jmcKimonoF);

        jmcMarca.setText("Marca");
        jmcMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmcMarcaActionPerformed(evt);
            }
        });
        jmcParticipacao.add(jmcMarca);

        jmCParticipacao.setText("Participações");
        jmCParticipacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmCParticipacaoActionPerformed(evt);
            }
        });
        jmcParticipacao.add(jmCParticipacao);

        jmcPatrimonio.setText("Patrimonio");
        jmcPatrimonio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmcPatrimonioActionPerformed(evt);
            }
        });
        jmcParticipacao.add(jmcPatrimonio);

        jmcPessoa.setText("Pessoa");
        jmcPessoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmcPessoaActionPerformed(evt);
            }
        });
        jmcParticipacao.add(jmcPessoa);

        jmcPolos.setText("Polos");
        jmcPolos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmcPolosActionPerformed(evt);
            }
        });
        jmcParticipacao.add(jmcPolos);

        jmcTamanho.setText("Tamanho");
        jmcTamanho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmcTamanhoActionPerformed(evt);
            }
        });
        jmcParticipacao.add(jmcTamanho);

        jMenuBar1.add(jmcParticipacao);

        jMenuListar.setText("Listar");

        jMLAcesso.setText("Acesso");
        jMLAcesso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMLAcessoActionPerformed(evt);
            }
        });
        jMenuListar.add(jMLAcesso);

        jMLAluno.setText("Aluno");
        jMLAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMLAlunoActionPerformed(evt);
            }
        });
        jMenuListar.add(jMLAluno);

        jmlCampeonato.setText("Competições");
        jmlCampeonato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmlCampeonatoActionPerformed(evt);
            }
        });
        jMenuListar.add(jmlCampeonato);

        jmlCargo.setText("Cargo");
        jmlCargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmlCargoActionPerformed(evt);
            }
        });
        jMenuListar.add(jmlCargo);

        jmlCategoriaKF.setText("Categoria uniforme");
        jmlCategoriaKF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmlCategoriaKFActionPerformed(evt);
            }
        });
        jMenuListar.add(jmlCategoriaKF);

        jmlCondicao.setText("Condicao");
        jmlCondicao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmlCondicaoActionPerformed(evt);
            }
        });
        jMenuListar.add(jmlCondicao);

        jmlCor.setText("Cor");
        jmlCor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmlCorActionPerformed(evt);
            }
        });
        jMenuListar.add(jmlCor);

        jmlEquipe.setText("Equipe");
        jmlEquipe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmlEquipeActionPerformed(evt);
            }
        });
        jMenuListar.add(jmlEquipe);

        jmlInvestidores.setText("Investidores");
        jmlInvestidores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmlInvestidoresActionPerformed(evt);
            }
        });
        jMenuListar.add(jmlInvestidores);

        jmlKimonoF.setText("Uniforme");
        jmlKimonoF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmlKimonoFActionPerformed(evt);
            }
        });
        jMenuListar.add(jmlKimonoF);

        jmlMarca.setText("Marcas");
        jmlMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmlMarcaActionPerformed(evt);
            }
        });
        jMenuListar.add(jmlMarca);

        jmlParticipacao.setText("Participação em Competições");
        jmlParticipacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmlParticipacaoActionPerformed(evt);
            }
        });
        jMenuListar.add(jmlParticipacao);

        jmlPatrimonio.setText("Patrimonio");
        jmlPatrimonio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmlPatrimonioActionPerformed(evt);
            }
        });
        jMenuListar.add(jmlPatrimonio);

        jmlPessoa.setText("Pessoas");
        jmlPessoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmlPessoaActionPerformed(evt);
            }
        });
        jMenuListar.add(jmlPessoa);

        jMenuItem27.setText("Polos");
        jMenuItem27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem27ActionPerformed(evt);
            }
        });
        jMenuListar.add(jMenuItem27);

        jmlTamano.setText("Tamanhos");
        jmlTamano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmlTamanoActionPerformed(evt);
            }
        });
        jMenuListar.add(jmlTamano);

        jMenuBar1.add(jMenuListar);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(156, 156, 156)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel2)))
                .addContainerGap(158, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(118, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(83, 83, 83))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMCAcessoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMCAcessoActionPerformed
        if (Formularios.cadAcesso == null)
            Formularios.cadAcesso = new CadAcesso();
        
        Formularios.cadAcesso.setVisible(true);
    }//GEN-LAST:event_jMCAcessoActionPerformed

    private void jMLAcessoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMLAcessoActionPerformed
        if (Formularios.listAcesso == null)
            Formularios.listAcesso = new ListAcesso();
        
        Formularios.listAcesso.setVisible(true);
    }//GEN-LAST:event_jMLAcessoActionPerformed

    private void jMCAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMCAlunoActionPerformed
        if (Formularios.cadAluno == null)
            Formularios.cadAluno = new CadAluno();
        
        Formularios.cadAluno.setVisible(true);
    }//GEN-LAST:event_jMCAlunoActionPerformed

    private void jMLAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMLAlunoActionPerformed
        if (Formularios.listAluno == null)
            Formularios.listAluno = new ListAluno();
        
        Formularios.listAluno.setVisible(true);
    }//GEN-LAST:event_jMLAlunoActionPerformed

    private void jmcCargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmcCargoActionPerformed
        if (Formularios.cadCargo == null)
            Formularios.cadCargo = new CadCargo();
        
        Formularios.cadCargo.setVisible(true);
    }//GEN-LAST:event_jmcCargoActionPerformed

    private void jmcCondicaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmcCondicaoActionPerformed
        if (Formularios.cadCondicao == null)
            Formularios.cadCondicao = new CadCondicao();
        
        Formularios.cadCondicao.setVisible(true);
    }//GEN-LAST:event_jmcCondicaoActionPerformed

    private void jmcCampeonatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmcCampeonatoActionPerformed
        if (Formularios.cadCampeonato == null)
            Formularios.cadCampeonato = new CadCampeonato();
        
        Formularios.cadCampeonato.setVisible(true);
    }//GEN-LAST:event_jmcCampeonatoActionPerformed

    private void jmcCategoriaKFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmcCategoriaKFActionPerformed
        if (Formularios.cadCategoriaKF == null)
            Formularios.cadCategoriaKF = new CadCategoriaU();
        
        Formularios.cadCategoriaKF.setVisible(true);
    }//GEN-LAST:event_jmcCategoriaKFActionPerformed

    private void jmcCorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmcCorActionPerformed
        if (Formularios.cadCor == null)
            Formularios.cadCor = new CadCor();
        
        Formularios.cadCor.setVisible(true);
    }//GEN-LAST:event_jmcCorActionPerformed

    private void jmcEquipeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmcEquipeActionPerformed
        if (Formularios.cadEquipe == null)
            Formularios.cadEquipe = new CadEquipe();
        
        Formularios.cadEquipe.setVisible(true);
    }//GEN-LAST:event_jmcEquipeActionPerformed

    private void jmcInvestidoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmcInvestidoresActionPerformed
        if (Formularios.cadInvestidores == null)
            Formularios.cadInvestidores = new CadInvestidores();
        
        Formularios.cadInvestidores.setVisible(true);
    }//GEN-LAST:event_jmcInvestidoresActionPerformed

    private void jmcKimonoFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmcKimonoFActionPerformed
        if (Formularios.cadKimonoF == null)
            Formularios.cadKimonoF = new CadUniforme();
        
        Formularios.cadKimonoF.setVisible(true);
    }//GEN-LAST:event_jmcKimonoFActionPerformed

    private void jmcMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmcMarcaActionPerformed
        if (Formularios.cadMarca == null)
            Formularios.cadMarca = new CadMarca();
        
        Formularios.cadMarca.setVisible(true);
    }//GEN-LAST:event_jmcMarcaActionPerformed

    private void jmCParticipacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmCParticipacaoActionPerformed
        if (Formularios.cadParticipacao == null)
            Formularios.cadParticipacao = new CadParticipacao();
        
        Formularios.cadParticipacao.setVisible(true);
    }//GEN-LAST:event_jmCParticipacaoActionPerformed

    private void jmcPatrimonioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmcPatrimonioActionPerformed
        if (Formularios.cadPatrimonio == null)
            Formularios.cadPatrimonio = new CadPatrimonio();
        
        Formularios.cadPatrimonio.setVisible(true);
    }//GEN-LAST:event_jmcPatrimonioActionPerformed

    private void jmcPessoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmcPessoaActionPerformed
        if (Formularios.cadPessoa == null)
            Formularios.cadPessoa = new CadPessoa();
        
        Formularios.cadPessoa.setVisible(true);
    }//GEN-LAST:event_jmcPessoaActionPerformed

    private void jmcPolosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmcPolosActionPerformed
        if (Formularios.cadPolos == null)
            Formularios.cadPolos = new CadPolos();
        
        Formularios.cadPolos.setVisible(true);
    }//GEN-LAST:event_jmcPolosActionPerformed

    private void jmcTamanhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmcTamanhoActionPerformed
        if (Formularios.cadTamanho == null)
            Formularios.cadTamanho = new CadTamanho();
        
        Formularios.cadTamanho.setVisible(true);
    }//GEN-LAST:event_jmcTamanhoActionPerformed

    private void jmlCampeonatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmlCampeonatoActionPerformed
        if (Formularios.listCampeonato == null)
            Formularios.listCampeonato = new ListCampeonato();
        
        Formularios.listCampeonato.setVisible(true);
    }//GEN-LAST:event_jmlCampeonatoActionPerformed

    private void jmlCargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmlCargoActionPerformed
        if (Formularios.listCargo == null)
            Formularios.listCargo = new ListCargo();
        
        Formularios.listCargo.setVisible(true);
    }//GEN-LAST:event_jmlCargoActionPerformed

    private void jmlCategoriaKFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmlCategoriaKFActionPerformed
        if (Formularios.listCategoriaKF == null)
            Formularios.listCategoriaKF = new ListCategoriaU();
        
        Formularios.listCategoriaKF.setVisible(true);
    }//GEN-LAST:event_jmlCategoriaKFActionPerformed

    private void jmlCondicaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmlCondicaoActionPerformed
        if (Formularios.listCondicao == null)
            Formularios.listCondicao = new ListCondicao();
        
        Formularios.listCondicao.setVisible(true);
    }//GEN-LAST:event_jmlCondicaoActionPerformed

    private void jmlCorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmlCorActionPerformed
        if (Formularios.listCor == null)
            Formularios.listCor = new ListCor();
        
        Formularios.listCor.setVisible(true);
    }//GEN-LAST:event_jmlCorActionPerformed

    private void jmlEquipeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmlEquipeActionPerformed
        if (Formularios.listEquipe == null)
            Formularios.listEquipe = new ListEquipe();
        
        Formularios.listEquipe.setVisible(true);
    }//GEN-LAST:event_jmlEquipeActionPerformed

    private void jmlInvestidoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmlInvestidoresActionPerformed
        if (Formularios.listInvestidores == null)
            Formularios.listInvestidores = new ListInvestidores();
        
        Formularios.listInvestidores.setVisible(true);
    }//GEN-LAST:event_jmlInvestidoresActionPerformed

    private void jmlKimonoFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmlKimonoFActionPerformed
        if (Formularios.listKimonoF == null)
            Formularios.listKimonoF = new ListUnifome();
        
        Formularios.listKimonoF.setVisible(true);
    }//GEN-LAST:event_jmlKimonoFActionPerformed

    private void jmlMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmlMarcaActionPerformed
        if (Formularios.listMarca == null)
            Formularios.listMarca = new ListMarca();
        
        Formularios.listMarca.setVisible(true);
    }//GEN-LAST:event_jmlMarcaActionPerformed

    private void jmlParticipacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmlParticipacaoActionPerformed
        if (Formularios.listParticipacao == null)
            Formularios.listParticipacao = new ListParticipacao();
        
        Formularios.listParticipacao.setVisible(true);
    }//GEN-LAST:event_jmlParticipacaoActionPerformed

    private void jmlPatrimonioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmlPatrimonioActionPerformed
        if (Formularios.listPatrimonio == null)
            Formularios.listPatrimonio = new ListPatrimonio();
        
        Formularios.listPatrimonio.setVisible(true);
    }//GEN-LAST:event_jmlPatrimonioActionPerformed

    private void jmlPessoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmlPessoaActionPerformed
        if (Formularios.listPessoa == null)
            Formularios.listPessoa = new ListPessoa();
        
        Formularios.listPessoa.setVisible(true);
    }//GEN-LAST:event_jmlPessoaActionPerformed

    private void jMenuItem27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem27ActionPerformed
        if (Formularios.listPolos == null)
            Formularios.listPolos = new ListPolos();
        
        Formularios.listPolos.setVisible(true);
    }//GEN-LAST:event_jMenuItem27ActionPerformed

    private void jmlTamanoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmlTamanoActionPerformed
        if (Formularios.listTamanho == null)
            Formularios.listTamanho = new ListTamanho();
        
        Formularios.listTamanho.setVisible(true);
    }//GEN-LAST:event_jmlTamanoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuProfessores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuProfessores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuProfessores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuProfessores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuProfessores().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuItem jMCAcesso;
    private javax.swing.JMenuItem jMCAluno;
    private javax.swing.JMenuItem jMLAcesso;
    private javax.swing.JMenuItem jMLAluno;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem27;
    private javax.swing.JMenu jMenuListar;
    private javax.swing.JMenuItem jmCParticipacao;
    private javax.swing.JMenuItem jmcCampeonato;
    private javax.swing.JMenuItem jmcCargo;
    private javax.swing.JMenuItem jmcCategoriaKF;
    private javax.swing.JMenuItem jmcCondicao;
    private javax.swing.JMenuItem jmcCor;
    private javax.swing.JMenuItem jmcEquipe;
    private javax.swing.JMenuItem jmcInvestidores;
    private javax.swing.JMenuItem jmcKimonoF;
    private javax.swing.JMenuItem jmcMarca;
    private javax.swing.JMenu jmcParticipacao;
    private javax.swing.JMenuItem jmcPatrimonio;
    private javax.swing.JMenuItem jmcPessoa;
    private javax.swing.JMenuItem jmcPolos;
    private javax.swing.JMenuItem jmcTamanho;
    private javax.swing.JMenuItem jmlCampeonato;
    private javax.swing.JMenuItem jmlCargo;
    private javax.swing.JMenuItem jmlCategoriaKF;
    private javax.swing.JMenuItem jmlCondicao;
    private javax.swing.JMenuItem jmlCor;
    private javax.swing.JMenuItem jmlEquipe;
    private javax.swing.JMenuItem jmlInvestidores;
    private javax.swing.JMenuItem jmlKimonoF;
    private javax.swing.JMenuItem jmlMarca;
    private javax.swing.JMenuItem jmlParticipacao;
    private javax.swing.JMenuItem jmlPatrimonio;
    private javax.swing.JMenuItem jmlPessoa;
    private javax.swing.JMenuItem jmlTamano;
    // End of variables declaration//GEN-END:variables
}
