/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.saipsc.Visao.MenuPrincipalP;

import com.mycompany.saipsc.Visao.Aluno.CadAluno;
import com.mycompany.saipsc.Visao.Aluno.ListAluno;
import com.mycompany.saipsc.ferramentas.BancoDeDadosMySql;
import com.mycompany.saipsc.ferramentas.Formularios;
import com.mycompany.saipsc.visao.Acesso.CadAcesso;
import com.mycompany.saipsc.visao.Acesso.ListAcesso;
import static java.awt.Frame.MAXIMIZED_BOTH;
import javax.swing.JOptionPane;

/**
 *
 * @author Batista
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
    
        setLocationRelativeTo(null);
        
        setExtendedState(MAXIMIZED_BOTH);
        
        if (!BancoDeDadosMySql.conectar()){
            JOptionPane.showMessageDialog(null, "Não foi possível conectar ao banco de dados. O sistema será finalizado.");
            System.exit(0);
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuCadastrar = new javax.swing.JMenu();
        jMCAcesso = new javax.swing.JMenuItem();
        jMCAluno = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenuItem15 = new javax.swing.JMenuItem();
        jMenuItem31 = new javax.swing.JMenuItem();
        jMenuListar = new javax.swing.JMenu();
        jMLAcesso = new javax.swing.JMenuItem();
        jMLAluno = new javax.swing.JMenuItem();
        jMenuItem18 = new javax.swing.JMenuItem();
        jMenuItem19 = new javax.swing.JMenuItem();
        jMenuItem20 = new javax.swing.JMenuItem();
        jMenuItem21 = new javax.swing.JMenuItem();
        jMenuItem22 = new javax.swing.JMenuItem();
        jMenuItem23 = new javax.swing.JMenuItem();
        jMenuItem24 = new javax.swing.JMenuItem();
        jMenuItem25 = new javax.swing.JMenuItem();
        jMenuItem26 = new javax.swing.JMenuItem();
        jMenuItem27 = new javax.swing.JMenuItem();
        jMenuItem28 = new javax.swing.JMenuItem();
        jMenuItem29 = new javax.swing.JMenuItem();
        jMenuItem30 = new javax.swing.JMenuItem();
        jMenuItem32 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setText("SAIPSC");

        jMenuCadastrar.setText("Cadastrar");

        jMCAcesso.setText("Acesso");
        jMCAcesso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMCAcessoActionPerformed(evt);
            }
        });
        jMenuCadastrar.add(jMCAcesso);

        jMCAluno.setText("Aluno");
        jMCAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMCAlunoActionPerformed(evt);
            }
        });
        jMenuCadastrar.add(jMCAluno);

        jMenuItem3.setText("jMenuItem3");
        jMenuCadastrar.add(jMenuItem3);

        jMenuItem4.setText("jMenuItem4");
        jMenuCadastrar.add(jMenuItem4);

        jMenuItem5.setText("jMenuItem5");
        jMenuCadastrar.add(jMenuItem5);

        jMenuItem6.setText("jMenuItem6");
        jMenuCadastrar.add(jMenuItem6);

        jMenuItem7.setText("jMenuItem7");
        jMenuCadastrar.add(jMenuItem7);

        jMenuItem8.setText("jMenuItem8");
        jMenuCadastrar.add(jMenuItem8);

        jMenuItem9.setText("jMenuItem9");
        jMenuCadastrar.add(jMenuItem9);

        jMenuItem10.setText("jMenuItem10");
        jMenuCadastrar.add(jMenuItem10);

        jMenuItem11.setText("jMenuItem11");
        jMenuCadastrar.add(jMenuItem11);

        jMenuItem12.setText("jMenuItem12");
        jMenuCadastrar.add(jMenuItem12);

        jMenuItem13.setText("jMenuItem13");
        jMenuCadastrar.add(jMenuItem13);

        jMenuItem14.setText("jMenuItem14");
        jMenuCadastrar.add(jMenuItem14);

        jMenuItem15.setText("jMenuItem15");
        jMenuCadastrar.add(jMenuItem15);

        jMenuItem31.setText("jMenuItem31");
        jMenuCadastrar.add(jMenuItem31);

        jMenuBar1.add(jMenuCadastrar);

        jMenuListar.setText("Listar");

        jMLAcesso.setText("Acesso");
        jMLAcesso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMLAcessoActionPerformed(evt);
            }
        });
        jMenuListar.add(jMLAcesso);

        jMLAluno.setText("Aluno");
        jMLAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMLAlunoActionPerformed(evt);
            }
        });
        jMenuListar.add(jMLAluno);

        jMenuItem18.setText("jMenuItem3");
        jMenuListar.add(jMenuItem18);

        jMenuItem19.setText("jMenuItem4");
        jMenuListar.add(jMenuItem19);

        jMenuItem20.setText("jMenuItem5");
        jMenuListar.add(jMenuItem20);

        jMenuItem21.setText("jMenuItem6");
        jMenuListar.add(jMenuItem21);

        jMenuItem22.setText("jMenuItem7");
        jMenuListar.add(jMenuItem22);

        jMenuItem23.setText("jMenuItem8");
        jMenuListar.add(jMenuItem23);

        jMenuItem24.setText("jMenuItem9");
        jMenuListar.add(jMenuItem24);

        jMenuItem25.setText("jMenuItem10");
        jMenuListar.add(jMenuItem25);

        jMenuItem26.setText("jMenuItem11");
        jMenuListar.add(jMenuItem26);

        jMenuItem27.setText("jMenuItem12");
        jMenuListar.add(jMenuItem27);

        jMenuItem28.setText("jMenuItem13");
        jMenuListar.add(jMenuItem28);

        jMenuItem29.setText("jMenuItem14");
        jMenuListar.add(jMenuItem29);

        jMenuItem30.setText("jMenuItem15");
        jMenuListar.add(jMenuItem30);

        jMenuItem32.setText("jMenuItem32");
        jMenuListar.add(jMenuItem32);

        jMenuBar1.add(jMenuListar);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 161, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 181, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMCAcessoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMCAcessoActionPerformed
        if (Formularios.cadAcesso == null)
            Formularios.cadAcesso = new CadAcesso();
        
        Formularios.cadAcesso.setVisible(true);
    }//GEN-LAST:event_jMCAcessoActionPerformed

    private void jMLAcessoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMLAcessoActionPerformed
        if (Formularios.listAcesso == null)
            Formularios.listAcesso = new ListAcesso();
        
        Formularios.listAcesso.setVisible(true);
    }//GEN-LAST:event_jMLAcessoActionPerformed

    private void jMCAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMCAlunoActionPerformed
        if (Formularios.cadAluno == null)
            Formularios.cadAluno = new CadAluno();
        
        Formularios.cadAluno.setVisible(true);
    }//GEN-LAST:event_jMCAlunoActionPerformed

    private void jMLAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMLAlunoActionPerformed
        if (Formularios.listAluno == null)
            Formularios.listAluno = new ListAluno();
        
        Formularios.listAluno.setVisible(true);
    }//GEN-LAST:event_jMLAlunoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuItem jMCAcesso;
    private javax.swing.JMenuItem jMCAluno;
    private javax.swing.JMenuItem jMLAcesso;
    private javax.swing.JMenuItem jMLAluno;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuCadastrar;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem18;
    private javax.swing.JMenuItem jMenuItem19;
    private javax.swing.JMenuItem jMenuItem20;
    private javax.swing.JMenuItem jMenuItem21;
    private javax.swing.JMenuItem jMenuItem22;
    private javax.swing.JMenuItem jMenuItem23;
    private javax.swing.JMenuItem jMenuItem24;
    private javax.swing.JMenuItem jMenuItem25;
    private javax.swing.JMenuItem jMenuItem26;
    private javax.swing.JMenuItem jMenuItem27;
    private javax.swing.JMenuItem jMenuItem28;
    private javax.swing.JMenuItem jMenuItem29;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem30;
    private javax.swing.JMenuItem jMenuItem31;
    private javax.swing.JMenuItem jMenuItem32;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JMenu jMenuListar;
    // End of variables declaration//GEN-END:variables
}
